import requests
import json
import time
from typing import Dict, Any, Optional, List
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter
from autoexpert.config import settings

class JulesClient:
    def __init__(self):
        self.api_key = settings.JULES_API_KEY
        self.base_url = settings.JULES_API_URL
        self.headers = {
            "Content-Type": "application/json",
            "X-Goog-Api-Key": self.api_key
        }
        
        # Configure retry strategy
        retry_strategy = Retry(
            total=5,
            backoff_factor=1,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["HEAD", "GET", "OPTIONS", "POST"]
        )
        adapter = HTTPAdapter(max_retries=retry_strategy)
        self.session = requests.Session()
        self.session.mount("https://", adapter)
        self.session.mount("http://", adapter)

    def list_sources(self) -> List[Dict[str, Any]]:
        response = self.session.get(f"{self.base_url}/sources", headers=self.headers)
        response.raise_for_status()
        return response.json().get("sources", [])

    def list_sessions(self) -> List[Dict[str, Any]]:
        response = self.session.get(f"{self.base_url}/sessions", headers=self.headers)
        response.raise_for_status()
        return response.json().get("sessions", [])

    def create_session(self, prompt: str, source_name: str, title: str = "AutoExpert Task") -> Dict[str, Any]:
        data = {
            "prompt": prompt,
            "sourceContext": {
                "source": source_name,
                "githubRepoContext": {
                    "startingBranch": "main"
                }
            },
            "title": title,
            "requirePlanApproval": False,
            "automationMode": "AUTO_CREATE_PR"
        }
        response = self.session.post(f"{self.base_url}/sessions", headers=self.headers, json=data)
        response.raise_for_status()
        return response.json()

    def get_session(self, session_id: str) -> Dict[str, Any]:
        response = self.session.get(f"{self.base_url}/sessions/{session_id}", headers=self.headers)
        response.raise_for_status()
        return response.json()

    def wait_for_session(self, session_id: str, timeout: int = 600, poll_interval: int = 10) -> Dict[str, Any]:
        start_time = time.time()
        while time.time() - start_time < timeout:
            session = self.get_session(session_id)
            # Checking if the session has completed by looking for outputs or status
            # Jules sessions usually produce outputs when done.
            if session.get("outputs"):
                return session
            
            # If there's an explicit state field in v1alpha (check common Google API patterns)
            # For now, we'll assume it's done if outputs exist or if it takes too long.
            # In a real scenario, we'd check for a 'state' like 'COMPLETED'.
            time.sleep(poll_interval)
        raise TimeoutError(f"Session {session_id} timed out.")

    def run_task(self, prompt: str, source_name: str) -> str:
        """Helper to run a task and return the resulting code or summary."""
        session = self.create_session(prompt, source_name)
        session_id = session["id"]
        completed_session = self.wait_for_session(session_id)
        
        # Extract content from outputs
        outputs = completed_session.get("outputs", [])
        if not outputs:
            return "No output generated by Jules."
        
        # Assuming the first output contains the result or PR info
        output = outputs[0]
        if "pullRequest" in output:
            return f"Created PR: {output['pullRequest']['url']}"
        
        return json.dumps(output, indent=2)

client = JulesClient()
